# Generated by Django 4.2.9 on 2024-04-18 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Prep_time', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('Difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('Vegetarian', models.BooleanField()),
                ('Recip_img', models.ImageField(upload_to='recipes/')),
                ('Descriptions', models.CharField(max_length=5000)),
            ],
        ),
    ]
